services:
  postgres:
    container_name: banking-postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_MULTIPLE_DATABASES: customer,notification,exchange
    volumes:
      - ./postgres:/data/postgres
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: banking-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge