server:
    port: 8081
spring:
    application:
        name: exchange
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5432/exchange
        username: admin
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    profiles:
        active: default
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true
api:
    nbp-url: https://api.nbp.pl

